# Generated by Django 5.2.14 on 2026-05-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='csv_username',
            field=models.CharField(db_index=True, default='admin', max_length=150),
            preserve_default=False,
        ),
    ]
